# إعدادات GitHub Pages
baseurl: ""
url: ""

# تحديد المجلد الذي يحتوي على الموقع
source: .

# تحديد المجلد الذي سيتم نشر الموقع فيه
destination: _site

# تحديد الفرع الذي سيتم استخدامه
branch: main

# تفعيل خيار include للتأكد من تضمين جميع الملفات
include:
  - ".nojekyll"

# تجاهل بعض الملفات والمجلدات
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - server.js